# Name of your application. Used to uniquely configure containers.
service: geosafe

# Name of the container image.
image: guimenezes/geosafe-app

# Deploy to these servers.
servers:
  web:
    - 104.248.119.167

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
proxy:
  app_port: 3000
  ssl: false # Mude para true quando tiver o domínio apontando para o IP
  # host: geosafe.seudominio.com.br

# Credentials for your image host.
registry:
  username: guimenezes
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://root@104.248.119.167

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    DB_HOST: 104.248.119.167
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

# Use a persistent storage volume.
volumes:
  - "geosafe_storage:/rails/storage"

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgres:14
    host: 104.248.119.167
    port: 5432
    env:
      clear:
        POSTGRES_USER: geosafe
        POSTGRES_DB: geosafe_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - geosafe_db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    host: 104.248.119.167
    port: 6379
    directories:
      - geosafe_redis_data:/data
