name: Ruby on Rails CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Lint with RuboCop
        run: bundle exec rubocop

      - name: Lint with ERB Lint
        run: bundle exec erb_lint --lint-all

      - name: Set up test database
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: password
        run: bundle exec rails db:prepare

      - name: Run RSpec tests
        env:
          RAILS_ENV: test
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: password
        run: bundle exec rspec
